import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Gauge, RefreshCw, AlertTriangle, Zap, CheckCircle, Flame } from "lucide-react";

export default function PressroomSimulator() {
  const [rpm, setRpm] = useState<number>(3600); // 0 to 12000 RPM
  const [cyanKey, setCyanKey] = useState<number>(65); // 0% to 100%
  const [magentaKey, setMagentaKey] = useState<number>(45);
  const [yellowKey, setYellowKey] = useState<number>(75);
  const [keyBlackKey, setKeyBlackKey] = useState<number>(30);

  const [cyanAngle, setCyanAngle] = useState<number>(15);
  const [magentaAngle, setMagentaAngle] = useState<number>(75);
  const [yellowAngle, setYellowAngle] = useState<number>(0);
  const [blackAngle, setBlackAngle] = useState<number>(45);
  const [lpi, setLpi] = useState<85 | 133 | 175>(133);

  const getHasMoire = () => {
    const diffCM = Math.abs(cyanAngle - magentaAngle) % 90;
    const diffCK = Math.abs(cyanAngle - blackAngle) % 90;
    const diffMK = Math.abs(magentaAngle - blackAngle) % 90;

    const minDiff = Math.min(
      diffCM, 90 - diffCM,
      diffCK, 90 - diffCK,
      diffMK, 90 - diffMK
    );
    return minDiff < 15;
  };
  const hasMoire = getHasMoire();
  
  // Target values for calibration game
  const targetC = 80;
  const targetM = 50;
  const targetY = 70;
  const targetK = 40;

  const [isCalibrated, setIsCalibrated] = useState<boolean>(false);
  const [runSheetsCount, setRunSheetsCount] = useState<number>(0);
  const [isPressRunning, setIsPressRunning] = useState<boolean>(true);

  // Check calibration alignment
  useEffect(() => {
    const errorMargin = 4; // allow +/- 4% deviation
    const cAlign = Math.abs(cyanKey - targetC) <= errorMargin;
    const mAlign = Math.abs(magentaKey - targetM) <= errorMargin;
    const yAlign = Math.abs(yellowKey - targetY) <= errorMargin;
    const kAlign = Math.abs(keyBlackKey - targetK) <= errorMargin;

    setIsCalibrated(cAlign && mAlign && yAlign && kAlign);
  }, [cyanKey, magentaKey, yellowKey, keyBlackKey]);

  // Sheets counter loop simulation
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (isPressRunning) {
      // higher RPM speeds up sheets run count
      const intervalMs = Math.max(50, 800 - (rpm / 12000) * 750);
      interval = setInterval(() => {
        setRunSheetsCount((prev) => prev + (isCalibrated ? 12 : 3)); // more efficient when calibrated!
      }, intervalMs);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isPressRunning, rpm, isCalibrated]);

  // Calculate dynamic diagnostics
  const wasteRate = isCalibrated ? 0.8 : Math.max(1.2, 18.5 - (rpm / 8000));
  const tempCelsius = 35 + (rpm / 12000) * 45 + (isCalibrated ? 0 : 8); // heat generated by machine speed
  const plateWear = Math.min(100, (runSheetsCount / 100000) * 100);

  const resetPressMetrics = () => {
    setRunSheetsCount(0);
    setCyanKey(65);
    setMagentaKey(45);
    setYellowKey(75);
    setKeyBlackKey(30);
  };

  const patternSize = lpi === 85 ? 20 : lpi === 133 ? 12 : 6;
  const patternCenter = patternSize / 2;
  const radiusMultiplier = lpi === 85 ? 7.5 : lpi === 133 ? 4.5 : 2.25;

  return (
    <div className="w-full text-left relative">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-6">
        <div>
          <span className="text-xs font-mono uppercase text-[#FF3E00] tracking-widest font-bold block mb-1">
            // Mechanical Output Module
          </span>
          <h3 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tighter uppercase leading-none select-none">
            Ink & Pressroom Simulator
          </h3>
          <p className="text-sm text-[#737373] mt-2 max-w-2xl">
            Simulate a commercial offset printing press run. Calibrate multi-channel ink fountain keys to match the press target, manage cylinder speed, and monitor real-time mechanical telemetry.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 bg-[#0F0F0F] border border-[#222] p-4 sm:p-6 md:p-8 rounded-lg relative overflow-hidden">
        
        {/* Left Column Controls - col-span-5 */}
        <div className="lg:col-span-5 space-y-6 flex flex-col justify-between">
          <div className="space-y-5">
            {/* Press Speed controller */}
            <div>
              <div className="flex justify-between items-center mb-1.5 font-mono text-[10px] text-white">
                <span className="text-[#FF3E00] uppercase font-bold">// CYLINDER SPEED (RPM):</span>
                <span>{rpm} RPM</span>
              </div>
              <input
                type="range"
                min={0}
                max={12000}
                step={200}
                value={rpm}
                onChange={(e) => {
                  const val = parseInt(e.target.value);
                  setRpm(val);
                  setIsPressRunning(val > 0);
                }}
                className="w-full h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#FF3E00]"
              />
              <div className="flex justify-between font-mono text-[7.5px] text-[#555] mt-1">
                <span>0 RPM (STOP)</span>
                <span>6000 RPM (OPTIMAL)</span>
                <span>12000 RPM (MAX CAPACITY)</span>
              </div>
            </div>

            {/* CMYK Ink Keys Balancing Puzzle */}
            <div className="border border-white/5 bg-[#111]/30 p-4 rounded-lg space-y-4">
              <div className="flex justify-between items-center border-b border-[#222] pb-2">
                <span className="font-mono text-[9px] text-[#A3A3A3] uppercase font-bold">
                  // Ink Key Calibration Deck
                </span>
                <span className={`font-mono text-[8px] px-1.5 py-0.5 uppercase ${
                  isCalibrated 
                    ? "bg-[#00FF00]/10 border border-[#00FF00]/30 text-[#00FF00]" 
                    : "bg-[#FF3E00]/10 border border-[#FF3E00]/30 text-[#FF3E00]"
                }`}>
                  {isCalibrated ? "[ Balanced ]" : "[ Out of Balance ]"}
                </span>
              </div>

              <p className="text-[10px] text-[#737373] leading-relaxed">
                Adjust sliders to match target specs (C:{targetC}%, M:{targetM}%, Y:{targetY}%, K:{targetK}%). Small indicators show direction to balance colors.
              </p>

              {/* Cyan key */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#00FFFF] font-bold">CYAN (C)</span>
                  <span className="text-white">
                    {cyanKey}% <span className="opacity-40">/ Target: {targetC}%</span>
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={0}
                    max={100}
                    value={cyanKey}
                    onChange={(e) => setCyanKey(parseInt(e.target.value))}
                    className="flex-1 h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#00FFFF]"
                  />
                  <span className="font-mono text-[8.5px] w-12 text-right">
                    {cyanKey > targetC + 4 ? "▼ Reduce" : cyanKey < targetC - 4 ? "▲ Raise" : "✓ Align"}
                  </span>
                </div>
              </div>

              {/* Magenta key */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#FF00FF] font-bold">MAGENTA (M)</span>
                  <span className="text-white">
                    {magentaKey}% <span className="opacity-40">/ Target: {targetM}%</span>
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={0}
                    max={100}
                    value={magentaKey}
                    onChange={(e) => setMagentaKey(parseInt(e.target.value))}
                    className="flex-1 h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#FF00FF]"
                  />
                  <span className="font-mono text-[8.5px] w-12 text-right">
                    {magentaKey > targetM + 4 ? "▼ Reduce" : magentaKey < targetM - 4 ? "▲ Raise" : "✓ Align"}
                  </span>
                </div>
              </div>

              {/* Yellow key */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#FFFF00] font-bold">YELLOW (Y)</span>
                  <span className="text-white">
                    {yellowKey}% <span className="opacity-40">/ Target: {targetY}%</span>
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={0}
                    max={100}
                    value={yellowKey}
                    onChange={(e) => setYellowKey(parseInt(e.target.value))}
                    className="flex-1 h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#FFFF00]"
                  />
                  <span className="font-mono text-[8.5px] w-12 text-right">
                    {yellowKey > targetY + 4 ? "▼ Reduce" : yellowKey < targetY - 4 ? "▲ Raise" : "✓ Align"}
                  </span>
                </div>
              </div>

              {/* Key Black key */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-white font-bold">BLACK (K)</span>
                  <span className="text-white">
                    {keyBlackKey}% <span className="opacity-40">/ Target: {targetK}%</span>
                  </span>
                </div>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={0}
                    max={100}
                    value={keyBlackKey}
                    onChange={(e) => setKeyBlackKey(parseInt(e.target.value))}
                    className="flex-1 h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#A3A3A3]"
                  />
                  <span className="font-mono text-[8.5px] w-12 text-right">
                    {keyBlackKey > targetK + 4 ? "▼ Reduce" : keyBlackKey < targetK - 4 ? "▲ Raise" : "✓ Align"}
                  </span>
                </div>
              </div>
            </div>

            {/* CMYK Screen Angles Deck */}
            <div className="border border-white/5 bg-[#111]/30 p-4 rounded-lg space-y-4">
              <div className="flex justify-between items-center border-b border-[#222] pb-2">
                <span className="font-mono text-[9px] text-[#A3A3A3] uppercase font-bold">
                  // CMYK Screen Angles Deck
                </span>
                <span className={`font-mono text-[8px] px-1.5 py-0.5 uppercase ${
                  hasMoire 
                    ? "bg-[#FF3E00]/10 border border-[#FF3E00]/30 text-[#FF3E00] animate-pulse" 
                    : "bg-[#00FF00]/10 border border-[#00FF00]/30 text-[#00FF00]"
                }`}>
                  {hasMoire ? "[ Moiré Mismatch ]" : "[ Angles Calibrated ]"}
                </span>
              </div>

              <p className="text-[10px] text-[#737373] leading-relaxed">
                Adjust screen rotation angles to avoid printing Moiré interference. Keep C/M/K screen angles at least 15° apart. (Standard offset print settings: C: 15°, M: 75°, Y: 0°, K: 45°).
              </p>

              {/* Cyan Angle */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#00FFFF] font-bold">CYAN SCREEN ANGLE</span>
                  <span className="text-white">{cyanAngle}°</span>
                </div>
                <input
                  type="range"
                  min={0}
                  max={90}
                  value={cyanAngle}
                  onChange={(e) => setCyanAngle(parseInt(e.target.value))}
                  className="w-full h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#00FFFF]"
                />
              </div>

              {/* Magenta Angle */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#FF00FF] font-bold">MAGENTA SCREEN ANGLE</span>
                  <span className="text-white">{magentaAngle}°</span>
                </div>
                <input
                  type="range"
                  min={0}
                  max={90}
                  value={magentaAngle}
                  onChange={(e) => setMagentaAngle(parseInt(e.target.value))}
                  className="w-full h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#FF00FF]"
                />
              </div>

              {/* Yellow Angle */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-[#FFFF00] font-bold">YELLOW SCREEN ANGLE</span>
                  <span className="text-white">{yellowAngle}°</span>
                </div>
                <input
                  type="range"
                  min={0}
                  max={90}
                  value={yellowAngle}
                  onChange={(e) => setYellowAngle(parseInt(e.target.value))}
                  className="w-full h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#FFFF00]"
                />
              </div>

              {/* Black Angle */}
              <div className="space-y-1">
                <div className="flex justify-between font-mono text-[8.5px]">
                  <span className="text-white font-bold">BLACK (KEY) SCREEN ANGLE</span>
                  <span className="text-white">{blackAngle}°</span>
                </div>
                <input
                  type="range"
                  min={0}
                  max={90}
                  value={blackAngle}
                  onChange={(e) => setBlackAngle(parseInt(e.target.value))}
                  className="w-full h-1 bg-[#1A1A1A] rounded-lg appearance-none cursor-pointer accent-[#A3A3A3]"
                />
              </div>
            </div>
          </div>

          {/* Reset buttons */}
          <div className="flex gap-3">
            <button
              onClick={resetPressMetrics}
              className="flex-grow flex items-center justify-center gap-2 bg-[#111]/30 hover:bg-[#1A1A1A] text-[#A3A3A3] hover:text-white border border-[#222] hover:border-[#FF3E00] py-2.5 font-mono text-[9px] uppercase tracking-wider transition-colors cursor-pointer rounded"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Reset Press</span>
            </button>
            <button
              onClick={() => setIsPressRunning(!isPressRunning)}
              className={`flex-grow font-mono text-[9px] uppercase tracking-wider py-2.5 rounded cursor-pointer transition-colors border ${
                isPressRunning 
                  ? "bg-[#FF3E00]/10 border-[#FF3E00]/40 text-[#FF3E00] hover:bg-[#FF3E00]/20" 
                  : "bg-white text-black border-white hover:bg-white/80"
              }`}
            >
              {isPressRunning ? "Emergency Stop" : "Start Press"}
            </button>
          </div>
        </div>

        {/* Right Column Visual Feedback & Diagnostics - col-span-7 */}
        <div className="lg:col-span-7 bg-[#111]/40 border border-white/5 rounded-xl p-5 md:p-6 flex flex-col justify-between relative overflow-hidden min-h-[460px]">
          {/* Subtle grid base lines */}
          <div className="absolute inset-0 bg-[radial-gradient(#1f1f1f_1px,transparent_1px)] [background-size:16px_16px] opacity-30 z-0 pointer-events-none" />

          {/* Visual Cylinder Animation and Calibration sample */}
          <div className="relative z-10 flex flex-col items-center justify-center flex-1 my-4 space-y-6">
            
            {/* Visual offset cylinders rotating */}
            <div className="flex justify-center items-center gap-6 select-none w-full max-w-sm">
              {/* Cylinder 1 (Plate) */}
              <div className="flex flex-col items-center">
                <div className="text-[7px] font-mono text-[#737373] uppercase mb-1">Plate Cylinder</div>
                <div className="relative w-16 h-16 rounded-full border border-white/10 bg-[#161616] flex items-center justify-center overflow-hidden">
                  <motion.div
                    animate={isPressRunning ? { rotate: 360 } : {}}
                    transition={isPressRunning ? { repeat: Infinity, duration: Math.max(0.5, 4 - (rpm / 12000) * 3.5), ease: "linear" } : {}}
                    className="absolute inset-1 rounded-full border-t border-r border-[#FF3E00]/40 flex items-center justify-center"
                  >
                    <div className="w-1.5 h-1.5 bg-[#FF3E00] rounded-full" />
                  </motion.div>
                  <span className="font-mono text-[9px] text-[#A3A3A3]">CMYK</span>
                </div>
              </div>

              {/* Cylinder 2 (Blanket - Transfer) */}
              <div className="flex flex-col items-center">
                <div className="text-[7px] font-mono text-[#737373] uppercase mb-1">Blanket Cylinder</div>
                <div className="relative w-20 h-20 rounded-full border border-white/10 bg-[#161616] flex items-center justify-center overflow-hidden">
                  <motion.div
                    animate={isPressRunning ? { rotate: -360 } : {}}
                    transition={isPressRunning ? { repeat: Infinity, duration: Math.max(0.6, 5 - (rpm / 12000) * 4.4), ease: "linear" } : {}}
                    className="absolute inset-1 rounded-full border-b border-l border-white/20 flex items-center justify-center"
                  >
                    <div className="w-2 h-1 bg-white/40" />
                  </motion.div>
                  <span className="font-mono text-[9px] text-white/50">Rubber</span>
                </div>
              </div>

              {/* Cylinder 3 (Impression) */}
              <div className="flex flex-col items-center">
                <div className="text-[7px] font-mono text-[#737373] uppercase mb-1">Impression</div>
                <div className="relative w-16 h-16 rounded-full border border-white/10 bg-[#161616] flex items-center justify-center overflow-hidden">
                  <motion.div
                    animate={isPressRunning ? { rotate: 360 } : {}}
                    transition={isPressRunning ? { repeat: Infinity, duration: Math.max(0.5, 4 - (rpm / 12000) * 3.5), ease: "linear" } : {}}
                    className="absolute inset-1.5 rounded-full border-t border-b border-white/10 flex items-center justify-center"
                  >
                    <div className="w-1.5 h-1.5 bg-white/30 rounded-full" />
                  </motion.div>
                  <span className="font-mono text-[9px] text-[#737373]">Steel</span>
                </div>
              </div>
            </div>

            {/* Print Color Matching Sample Box */}
            <div className="w-full max-w-sm border border-white/5 rounded-lg p-4 bg-black/60 relative overflow-hidden flex flex-col sm:flex-row gap-4 items-center justify-between">
              {/* Target color patch */}
              <div className="flex flex-col items-center space-y-1">
                <span className="text-[7px] font-mono text-[#737373] uppercase">Target Color Profile</span>
                <div 
                  className="w-14 h-14 border border-white/10 shadow-sm"
                  style={{
                    backgroundColor: `cmyk(${targetC}%, ${targetM}%, ${targetY}%, ${targetK}%)`,
                    background: `rgba(${255 - (targetC * 2.5) * (1 - targetK/100)}, ${255 - (targetM * 2.5) * (1 - targetK/100)}, ${255 - (targetY * 2.5) * (1 - targetK/100)}, 1)`
                  }}
                />
              </div>

              <div className="text-[#A3A3A3] text-center font-mono text-[16px] font-black">
                {isCalibrated ? (
                  <motion.div 
                    initial={{ scale: 0.8 }}
                    animate={{ scale: [0.8, 1.05, 1] }}
                    className="text-[#00FF00] flex items-center gap-1.5"
                  >
                    <CheckCircle className="w-4 h-4" /> INK REGISTERED
                  </motion.div>
                ) : (
                  <div className="text-[#FF3E00] flex items-center gap-1.5 animate-pulse text-xs uppercase">
                    <AlertTriangle className="w-4 h-4 shrink-0" /> Balance Ink Keys
                  </div>
                )}
              </div>

              {/* Live matching color patch */}
              <div className="flex flex-col items-center space-y-1">
                <span className="text-[7px] font-mono text-[#737373] uppercase">Fountain Ink output</span>
                <div 
                  className="w-14 h-14 border border-white/10 transition-all duration-300 shadow-sm"
                  style={{
                    backgroundColor: `cmyk(${cyanKey}%, ${magentaKey}%, ${yellowKey}%, ${keyBlackKey}%)`,
                    background: `rgba(${255 - (cyanKey * 2.5) * (1 - keyBlackKey/100)}, ${255 - (magentaKey * 2.5) * (1 - keyBlackKey/100)}, ${255 - (yellowKey * 2.5) * (1 - keyBlackKey/100)}, 1)`
                  }}
                />
              </div>
            </div>

            <div className="w-full max-w-sm h-36 border border-white/5 bg-[#161616] rounded-lg overflow-hidden flex flex-col justify-center items-center select-none relative group cursor-zoom-in">
              <span className="absolute top-2 left-2 font-mono text-[8px] text-[#A3A3A3] uppercase z-10 font-bold bg-black/60 px-1.5 py-0.5">// 400x Halftone Microscope Rosette</span>
              
              <div className="absolute top-2 right-2 flex gap-1 z-10 select-none">
                {([85, 133, 175] as const).map((item) => (
                  <button
                    key={item}
                    onClick={(e) => {
                      e.stopPropagation();
                      setLpi(item);
                    }}
                    className={`px-1.5 py-0.5 rounded-[1px] font-mono text-[7px] border cursor-pointer transition-colors ${
                      lpi === item 
                        ? 'bg-[#FF3E00] border-[#FF3E00] text-black font-black' 
                        : 'bg-black/60 border-white/10 text-[#A3A3A3] hover:text-white'
                    }`}
                  >
                    {item} LPI
                  </button>
                ))}
              </div>
              
              {/* Halftone background */}
              <div className="w-full h-full flex items-center justify-center relative bg-white">
                <svg className="absolute inset-0 w-full h-full" xmlns="http://www.w3.org/2000/svg">
                  <defs>
                    <pattern id="cyan-dots" x="0" y="0" width={patternSize} height={patternSize} patternUnits="userSpaceOnUse" patternTransform={`rotate(${cyanAngle})`}>
                      <circle cx={patternCenter} cy={patternCenter} r={Math.max(0.5, (cyanKey / 100) * radiusMultiplier)} fill="#00FFFF" opacity="0.8" />
                    </pattern>
                    <pattern id="magenta-dots" x="0" y="0" width={patternSize} height={patternSize} patternUnits="userSpaceOnUse" patternTransform={`rotate(${magentaAngle})`}>
                      <circle cx={patternCenter} cy={patternCenter} r={Math.max(0.5, (magentaKey / 100) * radiusMultiplier)} fill="#FF00FF" opacity="0.8" />
                    </pattern>
                    <pattern id="yellow-dots" x="0" y="0" width={patternSize} height={patternSize} patternUnits="userSpaceOnUse" patternTransform={`rotate(${yellowAngle})`}>
                      <circle cx={patternCenter} cy={patternCenter} r={Math.max(0.5, (yellowKey / 100) * radiusMultiplier)} fill="#FFFF00" opacity="0.8" />
                    </pattern>
                    <pattern id="black-dots" x="0" y="0" width={patternSize} height={patternSize} patternUnits="userSpaceOnUse" patternTransform={`rotate(${blackAngle})`}>
                      <circle cx={patternCenter} cy={patternCenter} r={Math.max(0.5, (keyBlackKey / 100) * radiusMultiplier)} fill="#111111" opacity="0.85" />
                    </pattern>
                  </defs>
                  <rect width="100%" height="100%" fill="url(#yellow-dots)" />
                  <rect width="100%" height="100%" fill="url(#cyan-dots)" />
                  <rect width="100%" height="100%" fill="url(#magenta-dots)" />
                  <rect width="100%" height="100%" fill="url(#black-dots)" />
                </svg>

                {/* Moiré Ripple bands simulation */}
                {hasMoire && (
                  <div className="absolute inset-0 pointer-events-none z-10 flex flex-col justify-center items-center bg-red-950/20 border border-red-500/25">
                    <span className="bg-red-600/90 text-white font-mono text-[7px] px-1.5 py-0.5 rounded-[1px] animate-pulse font-bold tracking-widest uppercase select-none">
                      ⚠️ Moiré Interference
                    </span>
                    <div className="absolute inset-0 opacity-[0.08] bg-[repeating-radial-gradient(circle_at_center,black_0px,black_8px,transparent_8px,transparent_16px)] pointer-events-none" />
                  </div>
                )}

                {/* Floating Pocket Loupe Magnifier Circle */}
                <div className="absolute w-24 h-24 rounded-full border-4 border-slate-700 bg-white shadow-2xl flex items-center justify-center overflow-hidden pointer-events-none scale-90 opacity-0 group-hover:opacity-100 group-hover:scale-105 transition-all duration-200 z-20">
                  <svg className="absolute w-full h-full" style={{ transform: "scale(2.5)" }}>
                    <rect width="100%" height="100%" fill="url(#yellow-dots)" />
                    <rect width="100%" height="100%" fill="url(#cyan-dots)" />
                    <rect width="100%" height="100%" fill="url(#magenta-dots)" />
                    <rect width="100%" height="100%" fill="url(#black-dots)" />
                  </svg>
                  <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/10 to-white/30" />
                </div>
              </div>
            </div>
          </div>

          {/* Telemetry Diagnostics Grid */}
          <div className="border-t border-white/5 pt-4">
            <span className="block font-mono text-[8px] text-[#FF3E00] uppercase font-bold mb-2">// Press Telemetry Logs:</span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-[9px]">
              {/* Running count */}
              <div className="border border-white/5 p-2 bg-[#111]/30 rounded">
                <span className="block text-[7px] text-[#737373]">SHEETS DELIVERED</span>
                <span className="text-white font-bold font-mono text-[11px] block mt-0.5">
                  {runSheetsCount.toLocaleString()}
                </span>
              </div>
              {/* Wastage */}
              <div className="border border-white/5 p-2 bg-[#111]/30 rounded">
                <span className="block text-[7px] text-[#737373]">WASTAGE OFFSET</span>
                <span className={`font-bold font-mono text-[11px] block mt-0.5 ${
                  wasteRate > 3 ? "text-[#FF3E00]" : "text-white"
                }`}>
                  {wasteRate.toFixed(2)}%
                </span>
              </div>
              {/* Temperature */}
              <div className="border border-white/5 p-2 bg-[#111]/30 rounded relative overflow-hidden">
                <span className="block text-[7px] text-[#737373]">ROLL TEMPERATURE</span>
                <span className="text-white font-bold font-mono text-[11px] block mt-0.5 flex items-center gap-1">
                  {tempCelsius.toFixed(1)}°C
                  {tempCelsius > 75 && <Flame className="w-3 text-[#FF3E00] animate-bounce" />}
                </span>
              </div>
              {/* Plate wear */}
              <div className="border border-white/5 p-2 bg-[#111]/30 rounded">
                <span className="block text-[7px] text-[#737373]">PLATE CALIPER WEAR</span>
                <span className="text-white font-bold font-mono text-[11px] block mt-0.5">
                  {plateWear.toFixed(2)}%
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
